name: app_heart_link
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 패키지 정보
  package_info_plus: ^8.3.0

  # 상태 관리
  # 라우팅
  # 바인딩
  get: 4.7.2

  collection: 1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SpoqaHanSans
      fonts:
        - asset: assets/font/SpoqaHanSansNeo-Light.otf
          weight: 300
        - asset: assets/font/SpoqaHanSansNeo-Regular.otf
          weight: 400
        - asset: assets/font/SpoqaHanSansNeo-Medium.otf
          weight: 500
        - asset: assets/font/SpoqaHanSansNeo-Bold.otf
          weight: 700

  assets:
    - assets/images/